# Generated by Django 3.1.5 on 2021-06-14 03:54

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_post_updated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=156, unique=True),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=254)),
                ('comment_text', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.expressions.Case, to='blogs.post')),
            ],
        ),
    ]
